### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by omidraha** [jwcliff/Inkscape_Exportxy#5]

**Comment by vmario89** [comment]
You need to put the *.py and *.inx file in extensions directory of inkscape. The default procedure for that is described in https://inkscape.org/gallery/=extension/

"To install a new extension, download and unpack the archive file. Copy the files into the directory listed at Edit > Preferences > System: User extensions. After a restart of Inkscape, the new extension will be available.

To learn about how to make one yourself, see here.

Some extensions may depend on other programs, that will need to be installed on your computer for them to work correctly. Usually, the author of the extension will provide instructions for this."

**Comment by omidraha** [comment]
Thanks.
